In [1]:
import pandas as pd

In [4]:
df = pd.read_csv('../Tablas Preparadas/Tabla1ConEstados.csv', sep=',')
df.head()

,order_id,customer_id,order_purchase_timestamp,order_item_id,product_id,seller_id,price,freight_value,product_category_name,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,2017-10-02 10:56:33,1.0,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,29.99,8.72,housewares,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,2018-07-24 20:41:37,1.0,595fac2a385ac33a80bd5114aec74eb8,289cdb325fb7e7f891c38608bf9e0962,118.70,22.76,perfumery,af07308b275d755c9edb36a90c618231,47813,barreiras,BA
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,2018-08-08 08:38:49,1.0,aa4383b373c6aca5d8797843e5594415,4869f7a5dfa277a7dca6462dcf3b52b2,159.90,19.22,auto,3a653a41f6f9fc3d2a113cf8398680e8,75265,vianopolis,GO
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,2017-11-18 19:28:06,1.0,d0b61bfb1de832b15ba9d266ca96e5b0,66922902710d126a0e7d26b0e3805106,45.00,27.20,pet_shop,7c142cf63193a1473d2e66489a9ae977,59296,sao goncalo do amarante,RN
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,2018-02-13 21:18:39,1.0,65266b2da20d04dbe00c5c2d3bb7859e,2c9e548be18521d1c43cde1c582c6de8,19.90,8.72,stationery,72632f0f9dd73dfee390c9b22eb56dd6,9195,santo andre,SP

In [6]:
df1= pd.read_csv('../Tablas Preparadas/EstadosYAbrev.csv',sep=';')
df1.head()

  abreviaturas    Estados
0           AC       Acre
1           AL    Alagoas
2           AM   Amazonas
3           BA      Bahía
4           CE      Ceara

In [7]:
nueva = pd.merge(df1, df, left_on='abreviaturas',right_on='customer_state', how='left')

In [9]:
nueva

,abreviaturas,Estados,order_id,customer_id,order_purchase_timestamp,order_item_id,product_id,seller_id,price,freight_value,product_category_name,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,AC,Acre,d445a6e277eaa62900bc18d453d96d76,c2cd065252fa7ad04274d9d69dd9c09e,2017-08-03 10:39:39,1.0,9afaad66aca8b0c79e4f084a89c9c92b,42bde9fef835393bb8a8849cb6b7f245,199.00,26.42,telephony,e808aa0ce98f33e671bf3e5b47756564,69918,rio branco,AC
1,AC,Acre,cab041d8d606d6c9d3165da578795340,888d2ebe1af2a8c93c75dae5dfc23719,2017-05-13 13:16:20,1.0,abe135ae574a8969994de86975004972,63ffcb71394dd8ea3872ed9ffda17c74,16.90,33.24,NaN,721d1092e1a6460c67e6a0e691d899a3,69900,rio branco,AC
2,AC,Acre,1a9f85c859f73034acc85057b4899a8e,f34e32b8604090d1c2a7f3b04c834807,2017-07-06 17:11:14,1.0,98ba4d6506268560a9b0a03b6ae02636,6179a28a13a726c29b3bf54c070dccab,300.00,61.27,luggage_accessories,785a8a410d6fc9661d66f7218a87229d,69900,rio branco,AC
3,AC,Acre,0d4628fecf8a76472ac1da3ebef92072,e4800add327af5e8c4c04f377fb1779a,2017-12-23 16:45:12,1.0,6de8bea41c968204fa93e4c2016d1bbb,aac29b1b99776be73c3049939652091d,239.00,77.19,electronics,df55ce6c8cb70b6d287154e726ad9066,69919,rio branco,AC
4,AC,Acre,40aecb2022cf80ba1efc9b0ddf5cd690,061a531d906f4bfb762be36757e41f7b,2017-07-17 18:19:50,1.0,75d6b6963340c6063f7f4cfcccfe6a30,cc419e0650a3c5ba77189a1882b7556a,56.99,25.43,perfumery,3168dc37da92585ed2bf29058b0cc143,69911,rio branco,AC
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110111,TO,Tocantins,2a19516124bb3d5f4d0d07555104e322,df8646b48feadbdaa69acd0715c9ed2b,2017-02-28 12:39:01,1.0,c21d0cfb10ff3cef881d63e1be43f260,7e1fb0a3ebfb01ffb3a7dae98bf3238d,120.99,18.28,sports_leisure,f17e55b784af893e2df1c2541f115e63,77670,divinopolis do tocantins,TO
110112,TO,Tocantins,c80bee063ac8e261dbf244fa3f710329,62ca610dbe5613c3e87ebf91eddf632f,2018-03-09 11:50:45,1.0,8cce4274f3868305ba6a25454b9cb2fd,65b081a070633e057c462abdd6fb9dd8,52.99,18.25,perfumery,bd7e86dd7c200cfba543520305150958,77410,gurupi,TO
110113,TO,Tocantins,cb6e8557d9afadd1aa602474dafddad8,21acca2de271c02fc746e1573535ed3a,2018-01-18 11:52:59,1.0,1b30d1c25bb529469aa0c83e326834b4,c8b0e2b0a7095e5d8219575d5e7e1181,145.99,33.47,auto,ba7594ffed6e0f18307c99b238ff57df,77320,taguatinga,TO
110114,TO,Tocantins,f1a1942c32bd91ad8368164ae571b8f7,9632f1ff07591588a9596b99f8515c03,2018-04-16 20:51:56,1.0,03d463c3dea9d1650ce0683b7c964b03,ea8482cd71df3c1969d7b9473ff13abc,21.99,37.04,telephony,1ef6a1d949703afd7a74347aed3b0503,77413,gurupi,TO
110115,TO,Tocantins,5bd233924f0b9c52492bd5a92e5ab2d3,d7475a536385854da614094f0bf12275,2018-05-30 13:23:37,1.0,5650f9e1f73d0a1c0176988cf2e950d5,2d518637f53161b973e01f56ea4bb88e,99.99,38.75,sports_leisure,17e3c70fc02567ec2d3831fa78e037c0,77829,araguaina,TO

In [11]:
nueva.drop(columns=['abreviaturas'], inplace=True)

In [12]:
nueva.drop(columns=['customer_state'],inplace=True)

In [14]:
nueva.rename(columns={'Estados':'customer_state'})

,customer_state,order_id,customer_id,order_purchase_timestamp,order_item_id,product_id,seller_id,price,freight_value,product_category_name,customer_unique_id,customer_zip_code_prefix,customer_city
0,Acre,d445a6e277eaa62900bc18d453d96d76,c2cd065252fa7ad04274d9d69dd9c09e,2017-08-03 10:39:39,1.0,9afaad66aca8b0c79e4f084a89c9c92b,42bde9fef835393bb8a8849cb6b7f245,199.00,26.42,telephony,e808aa0ce98f33e671bf3e5b47756564,69918,rio branco
1,Acre,cab041d8d606d6c9d3165da578795340,888d2ebe1af2a8c93c75dae5dfc23719,2017-05-13 13:16:20,1.0,abe135ae574a8969994de86975004972,63ffcb71394dd8ea3872ed9ffda17c74,16.90,33.24,NaN,721d1092e1a6460c67e6a0e691d899a3,69900,rio branco
2,Acre,1a9f85c859f73034acc85057b4899a8e,f34e32b8604090d1c2a7f3b04c834807,2017-07-06 17:11:14,1.0,98ba4d6506268560a9b0a03b6ae02636,6179a28a13a726c29b3bf54c070dccab,300.00,61.27,luggage_accessories,785a8a410d6fc9661d66f7218a87229d,69900,rio branco
3,Acre,0d4628fecf8a76472ac1da3ebef92072,e4800add327af5e8c4c04f377fb1779a,2017-12-23 16:45:12,1.0,6de8bea41c968204fa93e4c2016d1bbb,aac29b1b99776be73c3049939652091d,239.00,77.19,electronics,df55ce6c8cb70b6d287154e726ad9066,69919,rio branco
4,Acre,40aecb2022cf80ba1efc9b0ddf5cd690,061a531d906f4bfb762be36757e41f7b,2017-07-17 18:19:50,1.0,75d6b6963340c6063f7f4cfcccfe6a30,cc419e0650a3c5ba77189a1882b7556a,56.99,25.43,perfumery,3168dc37da92585ed2bf29058b0cc143,69911,rio branco
...,...,...,...,...,...,...,...,...,...,...,...,...,...
110111,Tocantins,2a19516124bb3d5f4d0d07555104e322,df8646b48feadbdaa69acd0715c9ed2b,2017-02-28 12:39:01,1.0,c21d0cfb10ff3cef881d63e1be43f260,7e1fb0a3ebfb01ffb3a7dae98bf3238d,120.99,18.28,sports_leisure,f17e55b784af893e2df1c2541f115e63,77670,divinopolis do tocantins
110112,Tocantins,c80bee063ac8e261dbf244fa3f710329,62ca610dbe5613c3e87ebf91eddf632f,2018-03-09 11:50:45,1.0,8cce4274f3868305ba6a25454b9cb2fd,65b081a070633e057c462abdd6fb9dd8,52.99,18.25,perfumery,bd7e86dd7c200cfba543520305150958,77410,gurupi
110113,Tocantins,cb6e8557d9afadd1aa602474dafddad8,21acca2de271c02fc746e1573535ed3a,2018-01-18 11:52:59,1.0,1b30d1c25bb529469aa0c83e326834b4,c8b0e2b0a7095e5d8219575d5e7e1181,145.99,33.47,auto,ba7594ffed6e0f18307c99b238ff57df,77320,taguatinga
110114,Tocantins,f1a1942c32bd91ad8368164ae571b8f7,9632f1ff07591588a9596b99f8515c03,2018-04-16 20:51:56,1.0,03d463c3dea9d1650ce0683b7c964b03,ea8482cd71df3c1969d7b9473ff13abc,21.99,37.04,telephony,1ef6a1d949703afd7a74347aed3b0503,77413,gurupi
110115,Tocantins,5bd233924f0b9c52492bd5a92e5ab2d3,d7475a536385854da614094f0bf12275,2018-05-30 13:23:37,1.0,5650f9e1f73d0a1c0176988cf2e950d5,2d518637f53161b973e01f56ea4bb88e,99.99,38.75,sports_leisure,17e3c70fc02567ec2d3831fa78e037c0,77829,araguaina

In [15]:
nueva.to_csv('Tabla1Final.csv', sep=';', index=False)